### ISSUE TITLE
User password should not be returned.

### ISSUE THREAD

**Issue by tolsam** [qlack/QLACK-Java#3]
User password should not be returned, even not hashed.
e.g. UserService#getUserByName

**Comment by imousmoutis** [comment]
The proposed way of consuming the QLACK services is by calling them in a service and map their result to your application DTOs and thus, edit the information as you wish (for example removing the password values).

Having the hashed password in the UserDTO would cause security issue only if your are exposing the result of the getUserByName directly to your frond end application...which you shouldn't do.

If we remove the password from the DTO, it might cause issues in other applications which will need the hashed passwords.
