### ISSUE TITLE
Swagger validator shows error when running on remote server. 

### ISSUE THREAD

**Issue by Rgkol** [qlack/QLACK-Java#4]
When creating the swagger-ui documentation, an error is shown in the bottom right corner.
This happens because the online validator used by swagger cannot access the private URL of the application. 

More info here: https://stackoverflow.com/questions/32188386/cant-read-from-file-issue-in-swagger-ui

![swagger-error](https://user-images.githubusercontent.com/45562574/67275667-c6a8cb00-f4cb-11e9-97f6-a198b6981b89.png)

**Comment by imousmoutis** [comment]
When compiling with the 'documentation' maven profile, the custom swagger-ui.js will be used in which the validation has been disabled in order to bypass it for internal applications.
