### ISSUE TITLE
qlack-fuse-content-manager deleteVersion fails

### ISSUE THREAD

**Issue by stephan-sch** [qlack/QLACK-Java#41]
When we delete a version by calling the VersionService.deleteVersion() following exception is thrown

`org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.eurodyn.qlack.fuse.cm.model.Version#1]`

Most probable cause is the DB trigger cm_version_deleted which is fired when a Version entry is deleted. 

Furthermore the tests that cover the VersionService.deleteVersion() do not catch the error as there is no interaction with a database in order the trigger to be fired.

**Comment by GeorgeVerr** [comment]
We have changes on content_manager_001.yaml.
Do not forget to delete the databasechangelog:  content_manager_001.yaml

**Comment by stephan-sch** [comment]
Works fine. Thank you
We can close this ticket.
