### ISSUE TITLE
qlack-fuse-content-manager scheduled deletion not configurable.

### ISSUE THREAD

**Issue by stephan-sch** [qlack/QLACK-Java#42]
Currently , qlack-fuse-content-manager implements a scheduler `cleanupFS()` in order to delete files from the filesystem as also db entries.  

The interval of this scheduler is hardcoded. It would better if the interval would be configurable through a property or maybe replacing it with a configurable cron expression.

**Comment by GeorgeVerr** [comment]
You can override the default value adding on application.properties
the below property `qlack.fuse.cm.cleanupInterval` , the timer is on milliseconds 

example on yaml
```
qlack:
  fuse:
      cm:
        cleanupInterval: 10000
```
