### ISSUE TITLE
Parametrize scheduler executions 

### ISSUE THREAD

**Issue by dimipapadeas** [qlack/QLACK-Java#7]
Parametrize the following scheduler to be able to set from application.properties

 /**
   * Check for QUEUED emails and send them.
   */
  @Scheduled(initialDelay = 30000, fixedDelay = 5000)
  public void checkAndSendQueued() {

Also consider to use application.properties for controlling  other Schedulers as well.

**Comment by imousmoutis** [comment]
Changes have been applied and are released with version 3.2.4.
