### ISSUE TITLE
Remove user from cache when changing user's password

### ISSUE THREAD

**Issue by vagelisne** [qlack/QLACK-Java#8]
When users change their password, they can log in with their the old password until the cache is invalidated. This happens because when `UserService.updateUser(userDTO, true, false)` is called the user is not removed from cache. The **AAAUsernamePasswordProvider** uses the authenticate method of Spring's **AbstractUserDetailsAuthenticationProvider** which authenticates the user using the cached entries. After the user logs in with their new password the old cache entry is replaced. Further information that may be relevant is that we call `AccountingService.terminateSessionByUserId(userDTO.getId());` right after the `updateUser`

**Comment by imousmoutis** [comment]
Hi @vagelisne . Thank you for reporting this issue.
We will provide a solution in the following days.

**Comment by imousmoutis** [comment]
Hi @vagelisne .
Are you using the qlack-fuse-search module to set up the security of the project or do you have your custom implementation?

If the first applies, you can invoke the CachingUserDetailsService.removeUser(username) method right after updating the password and the issue will be resolved.

**Comment by vagelisne** [comment]
Yes, we use qlack-fuse-security. Thank you for your response!
